### ISSUE TITLE
Feature Request: timer to allow contacts to be open for short time without alerting

### ISSUE THREAD

**Issue by motley74** [imbrianj/ready_for_rain#1]
Hello,

Are you still supporting and doing development for this app?  I would like to see if we can get a feature added to the app that will allow you to open a door (or any of the monitored contacts) while this check is active without it alerting.  I am testing an addition to the code to allow this and was just wanting to see if you are still actively supporting this app and if I should submit a PR to your repo or if I need to just publish the update on the community as a separate app.

There is no license specified in the code so not sure if you would be ok with a modified version being posted on the ST community forums, I would prefer to submit this to ST to be included in the original app if possible.  My intention would be to add an additional setting during configuration that would allow the user to set the amount of time to allow the contact to be open before sending the message.

**Comment by imbrianj** [comment]
Hi @motley74 .  Good call.  Yeah, I support it, but things have been quiet since it's a simple app that seemed to be pretty low-maintenance.  I can add that feature and CC you on the PR if you'd be interested in testing it?

The approval process for apps takes quite a long time (months), so you may want to install it locally till it's updated.

There's no license attached because it's unlicensed.  Truly "do what you want with it".  I think publishing on ST requires it to be under Apache, though.

**Comment by motley74** [comment]
Ok, well it is up to you if you want to add the feature or if you prefer I can submit a PR to your repo with the changes I have already made.  I am almost done testing my changes and have added a new configuration option to set the delay before sending an alert when a contact is open and added the code to make this work.

**Comment by imbrianj** [comment]
Ahh - if you already have it done, I'm happy to accept a PR.  I just added some to my local code, but we can at least compare notes.  I'll add you to the attribution if it's merged.

**Comment by motley74** [comment]
Ok, I will have a PR ready for you in a few minutes so you can review.  If you want you can accept my changes or if you know a better way that is fine to.  I will admit I am fairly new to ST but am a developer by profession so I do learn quickly.

**Comment by imbrianj** [comment]
https://github.com/imbrianj/ready_for_rain/pull/2
